# Generated by Django 3.2.4 on 2021-06-24 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_questions_topic_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='topic_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.topic'),
        ),
    ]
