# Generated by Django 3.2.4 on 2021-06-24 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_questions_topic_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='topic_id',
            new_name='topic',
        ),
    ]
