# Generated by Django 3.2.4 on 2021-06-24 12:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20210624_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.IntegerField(choices=[(0, 'easy'), (1, 'medium'), (2, 'hard')], validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(0)]),
        ),
    ]
