# Generated by Django 3.2.4 on 2021-06-24 12:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_alter_question_user_mark_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_user_mark',
            name='mark',
            field=models.IntegerField(choices=[(0, 'pending'), (1, 'need to revise'), (2, 'done')], default=0, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(0)]),
        ),
    ]
