# Generated by Django 3.2.4 on 2021-06-24 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_auto_20210624_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_asked_for_pair_programming',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='webapp.user'),
        ),
    ]
