# Generated by Django 3.2.4 on 2021-06-24 12:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_alter_user_asked_for_pair_programming_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark_update',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
