# Generated by Django 3.2.4 on 2021-06-28 07:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_rename_user_name_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark_update',
            name='previous_mark',
            field=models.IntegerField(choices=[(0, 'pending'), (1, 'need to revise'), (2, 'done')], default=0, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(0)]),
        ),
    ]
