# Generated by Django 3.2.4 on 2021-07-08 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_mark_update_previous_mark'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='question_user_mark',
            unique_together={('question_id', 'user_id')},
        ),
    ]
