# Generated by Django 3.2.4 on 2021-07-08 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_alter_question_user_mark_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pair_programmer',
            unique_together={('user_1', 'user_2')},
        ),
    ]
